name: gui-ci

on:
  push:
    paths:
      - '**'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build GUI
        run: pnpm run build

      - name: Run cargo tests
        run: cargo test --manifest-path src-tauri/Cargo.toml --all

      - name: Cypress (headless)
        uses: cypress-io/github-action@v6
        with:
          start: pnpm dev
          wait-on: 'http://localhost:1420'
